config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :channels do
    resources :rooms
  end
  resources :users

  post '/add_channel/:user_id/:channel_id', to: 'registrations#add_channel', as: "add_channel"
  delete '/drop_channel/:user_id/:channel_id', to: 'registrations#drop_channel', as: "drop_channel"

  post '/refresh', to: 'rooms#refresh', as: "refresh"
end

app/models/channel.rb
# Schema:
# name: string
# description: text

class Channel < ApplicationRecord
  validates :name, presence:true
  validates :description, presence:true   

  has_many :rooms, dependent: :destroy
  has_many :registrations, dependent: :destroy
  has_many :users, through: :registrations

  def self.ranked_subscribers 
    self.all.sort_by {|obj| -obj.users.length}
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_opentok

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @opentok
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def channel_params
      params.require(:channel).permit(:name, :description)
    end

    def set_opentok
      @opentok = get_opentok
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_with(model: channel, local: true) do |form| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, style: "width: 400px", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, style: "width: 400px", class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Done", class: "btn btn-primary", style: "width: 75px" %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<div style="display: flex">
  <h1>Channels</h1>
  <div style="flex: 1"></div>
  <%= button_to "New Channel", new_channel_path, method: :get, class: "btn btn-primary", style: "margin-right: 0px" %>
</div>

<div style="display: flex; flex-wrap: wrap">
  <% Channel.ranked_subscribers.each do |channel| %>
    <div class="card" style="width: 18rem; margin-top: 15px; margin-right: 15px">
      <div class="card-body">
        <h5 class="card-title"><%= channel.name %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= "#{channel.users.length} subscribers" %></h6>
        <p class="card-text"><%= truncate(channel.description, :length => 80) %></p>
      </div>

      <div style="display: flex; margin-bottom: 15px; margin-left: 15px">
        <%= button_to "Show", channel, method: :get, class: "btn btn-outline-primary", style: "margin-right: 10px" %>
        <% if channel.users.include? current_user %>
          <%= button_to "Drop", "/drop_channel/#{current_user.id}/#{channel.id}", method: :delete, class: "btn btn-secondary", style: "margin-right: 10px" %>
        <% else %>
          <%= button_to "Add", "/add_channel/#{current_user.id}/#{channel.id}", method: :post, class: "btn btn-primary", style: "margin-right: 10px" %>
        <% end %>
        <%# button_to "Edit", edit_channel_path(channel), method: :get, class: "btn btn-outline-primary", style: "margin-right: 10px" %>
        <%# link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  <% end %>
</div>

app/views/channels/new.html.erb
<div style="display: flex">
  <h1>New Channel</h1>
  <div style="flex: 1"></div>
  <%= link_to 'Back', channels_path, class: "btn btn-outline-secondary", style: "width: 75px; height: 38px" %>
</div>

<%= render 'form', channel: @channel %>

app/views/channels/show.html.erb
<div style="display: flex">
  <h1>Channel</h1>
  <div style="flex: 1"></div>
  <%= button_to "New Room", "/channels/#{@channel.id}/rooms/new", method: :get, class: "btn btn-primary", style: "margin-right: 15px" %>
  <%# button_to "Edit", edit_channel_path(@channel), method: :get, class: "btn btn-outline-secondary", style: "margin-right: 15px" %>
  <%= button_to "Back", channels_path, method: :get, class: "btn btn-outline-secondary", style: "margin-right: 0px" %>
</div>

<div class="card" style="width: 18rem; margin-top: 15px; margin-right: 15px">
  <div class="card-body">
    <h5 class="card-title"><%= @channel.name %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= "#{@channel.users.length} subscribers" %></h6>
    <h6 class="card-subtitle mb-2 text-muted"><%= "#{@channel.rooms.length} active rooms" %></h6>
    <p class="card-text"><%= truncate(@channel.description, :length => 80) %></p>
  </div>
</div>

<h4 style="margin-top: 15px">Active Rooms</h4>

<div style="display: flex">
  <% @channel.rooms.each do |room| %>
    <div class="card" style="width: 18rem; margin-top: 15px; margin-right: 15px">
      <div class="card-body">
        <h5 class="card-title"><%= room.name %></h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <% begin %>
            <% members = @opentok.streams.all(room.session_id).length %>
          <% rescue %>
          <% ensure %>
            <%= members %>
            <%= "users in room" %>
          <% end %>
        </h6>
        <p class="card-text"><%= truncate(room.description, :length => 80) %></p>
        <%= button_to "Join", channel_room_path(room.channel, room), method: :get, class: "btn btn-outline-secondary", style: "margin-right: 15px" %>
      </div>
    </div>
  <% end %>
</div>