config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :channels do
    resources :rooms
  end
  resources :users

  post '/add_channel/:user_id/:channel_id', to: 'registrations#add_channel', as: "add_channel"
  delete '/drop_channel/:user_id/:channel_id', to: 'registrations#drop_channel', as: "drop_channel"

  post '/refresh', to: 'rooms#refresh', as: "refresh"
end

app/models/user.rb
# Schema: 
# username: string
# name: string
# email: string
# password_hash: string
# bio: text

class User < ApplicationRecord

  # Validations
  validates :username, presence:true 
  validates :name, presence:true   
  validates :username, uniqueness:true
  validates :email, uniqueness:true
  validate :penn_email

  # Custom validatons
  def penn_email
    unless email.include? 'upenn.edu'      
      errors.add(:email, 'is not a Penn email') 
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         

  has_many :registrations, dependent: :destroy
  has_many :channels, through: :registrations

  has_one_attached :profile_picture
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    redirect_to current_user unless current_user == @user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :name, :email, :bio, :profile_picture)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>

  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, style: "width: 400px", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, style: "width: 400px", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, style: "width: 400px", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, style: "width: 400px", class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :profile_picture, class: "form-label" %>
    <%= form.file_field :profile_picture, class: "form-control" %>
  </div>

  <!-- <div class="field">
    <%= form.label :room_id %>
    <%= form.text_field :room_id %>
  </div> -->



  <div class="actions">
    <%= form.submit "Done", class: "btn btn-outline-primary", style: "width: 75px" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div style="display: flex">
  <h1>Edit User</h1>
  <div style="flex: 1"></div>
  <%= button_to "Cancel", @user, method: :get, class: "btn btn-outline-secondary", style: "width: 75px; margin-right: 10px" %>
</div>

<div style="display: flex; justify-content: center">
  <%= render 'form', user: @user %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<div style="display: flex; flex-direction: column">
  <% @users.each do |user| %>
    <div style="display: flex; align-items: center; border-top: 1px solid #bbb; padding-top: 5px; margin-top: 5px">
      <div style="margin-right: 20px">
        <% if user.profile_picture.attached? %>
          <%= image_tag user.profile_picture, :style => "width: 50px; height: 50px; object-fit: cover; border-radius: 50px" %>
        <% else %>
          <%= image_tag "default_pic.jpg", :style => "width: 50px; height: 50px; object-fit: cover; border-radius: 50px" %>
        <% end %>
      </div>
      <div><%= user.username %></div>
      <div style="flex: 1"></div>
      <%= button_to "Show", user, method: :get, class: "btn btn-outline-primary", style: "margin-right: 10px" %>
      <div><%# link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></div>
    </div>
  <% end %>
</div>

<!-- <%= link_to 'New User', new_user_path %> -->

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div style="display: flex; flex-direction: column; align-items: center">

  <div style="display: flex; width: 100%; align-items: center">
    <div style="flex: 1"></div>
    <p style="font-weight: bold; font-size: 18px"><%= @user.name %></p>
    <div style="flex: 1; justify-content: flex-end; align-items: center; display: flex">
      <%= button_to "Edit", edit_user_path(@user), method: :get, class: "btn btn-primary", style: "margin-right: 10px" if current_user == @user %>
      <%= button_to "Back", users_path, method: :get, class: "btn btn-outline-secondary", style: "margin-right: 10px" %>
    </div>
  </div>
  <% if @user.profile_picture.attached? %>
    <%= image_tag @user.profile_picture, :style => "width: 100px; height: 100px; object-fit: cover; border-radius: 50px" %>
  <% else %>
    <%= image_tag "default_pic.jpg", :style => "width: 100px; height: 100px; object-fit: cover; border-radius: 50px" %>
  <% end %>
  <div><%= "@" + @user.username %></div>
  <div><%= @user.email if current_user === @user %></div>
  <div><%= @user.bio %></div>

</div>

<h4>Subscribed Channels</h4>

<div style="display: flex; flex-wrap: wrap">
  <% @user.channels.each do |channel| %>
    <div class="card" style="width: 18rem; margin-top: 15px; margin-right: 15px">
      <div class="card-body">
        <h5 class="card-title"><%= channel.name %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= "#{channel.users.length} subscribers" %></h6>
        <p class="card-text"><%= truncate(channel.description, :length => 80) %></p>
      </div>

      <div style="display: flex; margin-bottom: 15px; margin-left: 15px">
        <%= button_to "Show", channel, method: :get, class: "btn btn-outline-primary", style: "margin-right: 10px" %>

        <% if channel.users.include? current_user %>
          <%= button_to "Drop", "/drop_channel/#{@user.id}/#{channel.id}", method: :delete, class: "btn btn-secondary", style: "margin-right: 10px" %>
        <% else %>
          <%= button_to "Add", "/add_channel/#{@user.id}/#{channel.id}", method: :post, class: "btn btn-primary", style: "margin-right: 10px" %>
        <% end %>

        <%# button_to "Edit", edit_channel_path(channel), method: :get, class: "btn btn-outline-primary", style: "margin-right: 10px" %>
      </div>
    </div>
  <% end %>
</div>