config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :channels do
    resources :rooms
  end
  resources :users

  post '/add_channel/:user_id/:channel_id', to: 'registrations#add_channel', as: "add_channel"
  delete '/drop_channel/:user_id/:channel_id', to: 'registrations#drop_channel', as: "drop_channel"

  post '/refresh', to: 'rooms#refresh', as: "refresh"
end

app/models/room.rb
require "opentok"

# Schema:
# name: string
# description: text
# session_id: integer
# channel: references

class Room < ApplicationRecord

  # validations
  validates :name, presence:true   

  # relationships
  belongs_to :channel
  has_many :users

  # initializes OpenTok API
  def config_opentok
    tries = 3
    begin
      @opentok = OpenTok::OpenTok.new Rails.application.credentials.vonage[:api_key], Rails.application.credentials.vonage[:secret]
      logger.debug "opentok connected."
     rescue Errno::ETIMEDOUT => e
      log.error e 
      tries -= 1
        if tries > 0
          logger.debug "retrying opentok.new..."
        retry 
        else
          logger.debug "opentok.new timed out..."
          puts "ERROR: #{e.message}" 
        end
    end
    @opentok
  end

  # getter: returns session
  def session
    @session
  end

  # setter: sets session
  def session=(new_session)
    @session = new_session
  end
end

app/controllers/rooms_controller.rb
require "opentok"
require "json"

class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_opentok

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
    @channel = Channel.find(params[:channel_id])
  end


  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @token = @opentok.generate_token @room.session_id, { name: current_user.name }
    @opentok

    begin
      info = @opentok.streams.all(@room.session_id)
    rescue
    ensure
      if info
        arr = []
        info.each do |stream|
          jinfo = JSON.parse(stream.to_json)
          username = jinfo["name"]
          user = User.find_by(username: username)
          arr.push(user)
        end
        @streams = arr
      else
        @streams = []
      end
    end
  end

  # GET /rooms/new
  def new
    @channel = Channel.find(params[:channel_id])
    @room = @channel.rooms.build
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @channel = Channel.find(params[:channel_id])
    @room = @channel.rooms.build(room_params)
    @session = @opentok.create_session
    @room.session_id = @session.session_id

    respond_to do |format|
      if @room.save
        format.html { redirect_to channel_room_path(@room.channel, @room), notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to channel_room_path(@room.channel, @room), notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to channel_rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :description, :channel_id, :vonage_session)
    end

    def set_opentok
      @opentok = get_opentok
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: [room.channel, room], local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, style: "width: 400px", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, style: "width: 400px", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :channel_id %>
    <%= form.text_field :channel_id, style: "width: 400px", class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Done", class: "btn btn-primary", style: "width: 75px" %>
  </div>

<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', channel_room_path(@room.channel, @room) %> |
<%= link_to 'Back', channel_rooms_path %>

app/views/rooms/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Rooms</h1>

<h4>All</h4>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Channel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.description %></td>
        <td><%= room.channel %></td>
        <td><%= link_to 'Show', channel_room_path(room.channel, room) %></td>
        <td><%= link_to 'Edit', edit_channel_room_path(room.channel, room) %></td>
        <td><%= link_to 'Destroy', channel_room_path(room.channel, room), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_channel_room_path %>

app/views/rooms/new.html.erb
<div style="display: flex">
  <h1>New Room</h1>
  <div style="flex: 1"></div>
  <%= link_to 'Back', @channel, class: "btn btn-outline-secondary", style: "width: 75px; height: 38px" %>
</div>

<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<!-- Video Display -->
<div id="videos" style="position: relative;
    width: 600px;
    height: 400px;
    margin-left: auto;
    margin-right: auto;
    display: flex
    ">

    <div id="subscriber" style="position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    z-index: 10;"></div>

    <div id="publisher" style="position: absolute;
    width: 360px;
    height: 240px;
    bottom: 10px;
    left: 10px;
    z-index: 100;
    border: 3px solid white;
    border-radius: 3px;"></div>
</div>

<!-- User subscription stream -->
<% begin %>
  <%# @opentok.streams.all(@room.session_id)  if @opentok.streams.all(@room.session_id) %>
  <% @streams.each do |user| %>
    <div style="display: flex; align-items: center; border-top: 1px solid #bbb; padding-top: 5px; margin-top: 5px">
      <div style="margin-right: 20px">
        <% if user.profile_picture.attached? %>
          <%= image_tag user.profile_picture, :style => "width: 50px; height: 50px; object-fit: cover; border-radius: 50px" %>
        <% else %>
          <%= image_tag "default_pic.jpg", :style => "width: 50px; height: 50px; object-fit: cover; border-radius: 50px" %>
        <% end %>
      </div>
      <div><%= user.username %></div>
      <div style="flex: 1"></div>
      <%= button_to "Show", user, method: :get, class: "btn btn-outline-primary", style: "margin-right: 10px" %>
    </div>
  <% end %>
<% rescue %>
<% ensure %>
<% end %>


<script>
  var apiKey = "<%= Rails.application.credentials.vonage[:api_key] %>";
  var sessionId = "<%= @room.session_id %>";
  var token = "<%= @token %>";

  // Handling all of our errors here by alerting them
  function handleError(error) {
    if (error) {
      alert(error.message);
    }
  }

  initializeSession();

  function initializeSession() {
    var session = OT.initSession(apiKey, sessionId);

    // Subscribe to a newly created stream
    session.on('streamCreated', function(event) {
      session.subscribe(event.stream, 'subscriber', {
        insertMode: 'append',
        width: '100%',
        height: '100%'
      }, handleError);
    });

    // Create a publisher
    var publisher = OT.initPublisher('publisher', {
      name: "<%= current_user.username %>",
      style: {
        insertMode: 'append',
        width: '100%',
        height: '100%'
      }
    }, handleError);

    // Connect to the session
    session.connect(token, function(error) {
      // If the connection is successful, initialize a publisher and publish to the session
      if (error) {
        handleError(error);
      } else {
        session.publish(publisher, handleError);
      }
    });
  }
</script>